version: '3'

services:
    calendar:
        image: 'bbalbon/trippy_advisors_calendar_widget:calendar'
        depends_on:
            - 'database'
        ports:
            - '1128:1128'
    
    database:
        image: mongo:latest